from userauths.models import AssessmentQuestion, Choice
def seed_questions():
    q = AssessmentQuestion.objects.create(level="1", type="MC", text="What is the best way to demonstrate empathy during patient interactions?")
    Choice.objects.create(question=q, text="Listen actively and acknowledge their concerns", is_correct=True)
    Choice.objects.create(question=q, text="Speak quickly to save time", is_correct=False)
    Choice.objects.create(question=q, text="Use medical jargon to show knowledge", is_correct=False)
    Choice.objects.create(question=q, text="Avoid eye contact to reduce pressure", is_correct=False)
    q = AssessmentQuestion.objects.create(level="1", type="MC", text="How should you respond when a patient becomes verbally aggressive?")
    Choice.objects.create(question=q, text="Stay calm and professionally de-escalate the situation", is_correct=True)
    Choice.objects.create(question=q, text="Raise your voice in return", is_correct=False)
    Choice.objects.create(question=q, text="Ignore the patient completely", is_correct=False)
    Choice.objects.create(question=q, text="Leave the room immediately", is_correct=False)
    q = AssessmentQuestion.objects.create(level="1", type="MC", text="What does professionalism mean in a healthcare setting?")
    Choice.objects.create(question=q, text="Following policy at all costs", is_correct=False)
    Choice.objects.create(question=q, text="Speaking with tact, respect, and accountability", is_correct=True)
    Choice.objects.create(question=q, text="Always being right in front of patients", is_correct=False)
    Choice.objects.create(question=q, text="Prioritizing speed over communication", is_correct=False)
    q = AssessmentQuestion.objects.create(level="1", type="MC", text="What’s the best way to handle feedback or criticism at work?")
    Choice.objects.create(question=q, text="Become defensive", is_correct=False)
    Choice.objects.create(question=q, text="Ignore it if you disagree", is_correct=False)
    Choice.objects.create(question=q, text="Accept it respectfully and reflect", is_correct=True)
    Choice.objects.create(question=q, text="Deny responsibility immediately", is_correct=False)
    q = AssessmentQuestion.objects.create(level="1", type="MC", text="How should new hires present themselves at interviews?")
    Choice.objects.create(question=q, text="Wear casual fuzzy slippers", is_correct=False)
    Choice.objects.create(question=q, text="Be fully present, respectful, and engaged", is_correct=True)
    Choice.objects.create(question=q, text="Say 'I don’t know' frequently", is_correct=False)
    Choice.objects.create(question=q, text="Avoid eye contact to seem humble", is_correct=False)
    q = AssessmentQuestion.objects.create(level="1", type="MC", text="How can a nurse show accountability?")
    Choice.objects.create(question=q, text="By blaming coworkers for mistakes", is_correct=False)
    Choice.objects.create(question=q, text="By acknowledging their own missteps and improving", is_correct=True)
    Choice.objects.create(question=q, text="By avoiding responsibility", is_correct=False)
    Choice.objects.create(question=q, text="By dismissing patient concerns", is_correct=False)
    q = AssessmentQuestion.objects.create(level="1", type="MC", text="What is the role of respectful communication in professionalism?")
    Choice.objects.create(question=q, text="It builds trust with patients and coworkers", is_correct=True)
    Choice.objects.create(question=q, text="It’s less important than being efficient", is_correct=False)
    Choice.objects.create(question=q, text="It can be replaced with body language", is_correct=False)
    Choice.objects.create(question=q, text="It only matters in leadership roles", is_correct=False)
    q = AssessmentQuestion.objects.create(level="1", type="MC", text="Which behavior is least professional in a medical interview?")
    Choice.objects.create(question=q, text="Asking thoughtful questions", is_correct=False)
    Choice.objects.create(question=q, text="Wearing clean scrubs", is_correct=False)
    Choice.objects.create(question=q, text="Using slang and showing disinterest", is_correct=True)
    Choice.objects.create(question=q, text="Maintaining eye contact", is_correct=False)
    q = AssessmentQuestion.objects.create(level="1", type="MC", text="What should you do when you make a mistake with a patient?")
    Choice.objects.create(question=q, text="Hide the mistake", is_correct=False)
    Choice.objects.create(question=q, text="Blame another staff member", is_correct=False)
    Choice.objects.create(question=q, text="Acknowledge and report it appropriately", is_correct=True)
    Choice.objects.create(question=q, text="Dismiss it as minor", is_correct=False)
    q = AssessmentQuestion.objects.create(level="1", type="MC", text="What is the foundation of soft skills in healthcare?")
    Choice.objects.create(question=q, text="Advanced medical knowledge", is_correct=False)
    Choice.objects.create(question=q, text="High salary motivation", is_correct=False)
    Choice.objects.create(question=q, text="Effective communication and empathy", is_correct=True)
    Choice.objects.create(question=q, text="Working alone", is_correct=False)
    q = AssessmentQuestion.objects.create(level="2", type="MC", text="What is a key trait of effective healthcare teamwork?")
    Choice.objects.create(question=q, text="Clear communication and role definition", is_correct=True)
    Choice.objects.create(question=q, text="Avoiding conflict at all cost", is_correct=False)
    Choice.objects.create(question=q, text="Working alone to finish tasks faster", is_correct=False)
    Choice.objects.create(question=q, text="Only following physician instructions", is_correct=False)
    q = AssessmentQuestion.objects.create(level="2", type="MC", text="How should you handle a situation when a team member makes a mistake?")
    Choice.objects.create(question=q, text="Address it respectfully and report if needed", is_correct=True)
    Choice.objects.create(question=q, text="Confront them harshly in public", is_correct=False)
    Choice.objects.create(question=q, text="Ignore it and move on", is_correct=False)
    Choice.objects.create(question=q, text="Take over all their responsibilities", is_correct=False)
    q = AssessmentQuestion.objects.create(level="2", type="MC", text="What’s the best way to handle patient training for home care?")
    Choice.objects.create(question=q, text="Rush through the steps", is_correct=False)
    Choice.objects.create(question=q, text="Hand off to another department", is_correct=False)
    Choice.objects.create(question=q, text="Provide consistent, personalized instruction", is_correct=True)
    Choice.objects.create(question=q, text="Let them figure it out alone", is_correct=False)
    q = AssessmentQuestion.objects.create(level="2", type="MC", text="What’s an example of going above and beyond for a patient?")
    Choice.objects.create(question=q, text="Only answering during office hours", is_correct=False)
    Choice.objects.create(question=q, text="FaceTiming and visiting when needed", is_correct=True)
    Choice.objects.create(question=q, text="Ignoring after-hours calls", is_correct=False)
    Choice.objects.create(question=q, text="Telling them to ask someone else", is_correct=False)
    q = AssessmentQuestion.objects.create(level="2", type="MC", text="How should team members approach disagreements?")
    Choice.objects.create(question=q, text="With open discussion and mutual respect", is_correct=True)
    Choice.objects.create(question=q, text="By avoiding the issue entirely", is_correct=False)
    Choice.objects.create(question=q, text="By going to a supervisor first", is_correct=False)
    Choice.objects.create(question=q, text="With sarcasm and dismissal", is_correct=False)
    q = AssessmentQuestion.objects.create(level="2", type="MC", text="Which behavior supports team retention?")
    Choice.objects.create(question=q, text="Supportive communication with colleagues", is_correct=True)
    Choice.objects.create(question=q, text="Gossiping about coworkers", is_correct=False)
    Choice.objects.create(question=q, text="Criticizing team efforts", is_correct=False)
    Choice.objects.create(question=q, text="Avoiding new employees", is_correct=False)
    q = AssessmentQuestion.objects.create(level="2", type="MC", text="Which of these best represents patient-centered care?")
    Choice.objects.create(question=q, text="Making every decision without patient input", is_correct=False)
    Choice.objects.create(question=q, text="Assuming you know best", is_correct=False)
    Choice.objects.create(question=q, text="Listening to the patient and adapting care plans", is_correct=True)
    Choice.objects.create(question=q, text="Always sticking to routine", is_correct=False)
    q = AssessmentQuestion.objects.create(level="2", type="MC", text="What kind of environment should a nurse create with patients?")
    Choice.objects.create(question=q, text="Authoritative and cold", is_correct=False)
    Choice.objects.create(question=q, text="Collaborative and compassionate", is_correct=True)
    Choice.objects.create(question=q, text="Aloof and minimal", is_correct=False)
    Choice.objects.create(question=q, text="Strictly business", is_correct=False)
    q = AssessmentQuestion.objects.create(level="2", type="MC", text="When a patient is unhappy about care, what’s the best next step?")
    Choice.objects.create(question=q, text="Ignore them", is_correct=False)
    Choice.objects.create(question=q, text="Calmly listen and explain the care process", is_correct=True)
    Choice.objects.create(question=q, text="Tell them to switch providers", is_correct=False)
    Choice.objects.create(question=q, text="Redirect them to billing", is_correct=False)
    q = AssessmentQuestion.objects.create(level="2", type="MC", text="Why is time management important for quality care?")
    Choice.objects.create(question=q, text="It helps staff get out early", is_correct=False)
    Choice.objects.create(question=q, text="It shows you care about patients’ time", is_correct=True)
    Choice.objects.create(question=q, text="It impresses management", is_correct=False)
    Choice.objects.create(question=q, text="It prevents communication", is_correct=False)
    AssessmentQuestion.objects.create(level="3", type="OE", text="A patient refuses treatment due to religious beliefs. What do you do?")
    AssessmentQuestion.objects.create(level="3", type="OE", text="You witness a coworker falsifying patient records. How do you respond?")
    AssessmentQuestion.objects.create(level="3", type="OE", text="A family member asks for information that you're not authorized to give. What do you say?")
    AssessmentQuestion.objects.create(level="3", type="OE", text="You suspect abuse but the patient denies it. What steps do you take?")
    AssessmentQuestion.objects.create(level="3", type="OE", text="Describe how you would de-escalate a situation where a patient blames you for an accident involving their property.")
    AssessmentQuestion.objects.create(level="3", type="OE", text="You're assigned a patient who has been disrespectful in the past. How do you handle their care?")
    AssessmentQuestion.objects.create(level="3", type="OE", text="How would you handle a situation where your team is not collaborating effectively?")
    AssessmentQuestion.objects.create(level="3", type="OE", text="A patient accuses you of discrimination. How do you address this?")
    AssessmentQuestion.objects.create(level="3", type="OE", text="You’re emotionally overwhelmed after a shift. What is your self-care plan?")
    AssessmentQuestion.objects.create(level="3", type="OE", text="How do you balance empathy with enforcing medical policies?")
    print("✅ All 30 assessment questions inserted.")
seed_questions()