# Generated by Django 4.2.7 on 2025-05-02 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_profile_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Soft Skills / Professionalism'), ('2', 'Teamwork / Quality of Care'), ('3', 'Ethical Decision-Making')], max_length=1)),
                ('type', models.CharField(choices=[('MC', 'Multiple Choice'), ('OE', 'Open Ended')], max_length=2)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_responses', to='userauths.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauths.assessmentquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='userauths.assessmentquestion')),
            ],
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='selected_answers',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.RemoveField(
            model_name='result',
            name='user',
        ),
        migrations.AddField(
            model_name='result',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='userauths.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='level',
            field=models.CharField(choices=[('1', 'Soft Skills / Professionalism'), ('2', 'Teamwork / Quality of Care'), ('3', 'Ethical Decision-Making')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.choice'),
        ),
    ]
