# Generated by Django 4.2.7 on 2025-05-02 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_assessmentquestion_assessmentresponse_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(choices=[('1', 'Soft Skills / Professionalism'), ('2', 'Teamwork / Quality of Care'), ('3', 'Ethical Decision-Making')], default='1', max_length=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='userauths.profile')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='userauths.assessment'),
        ),
    ]
